name: pytest
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ">= 3.8 < 3.12"
      - name: Install torchcvnn dependencies
        run: |
          python -m pip install .
      - name: Install pytest dependencies
        run: |
          pip install -r tests/requirements.txt
      - name: Run pytest tests
        run: cd tests && pytest --doctest-modules --junitxml=junit/test-results.xml --cov=torchcvnn --cov-report=xml --cov-report=html
